currency:
    token: 42e6c99942d1119371116c91fc32ac57
    url:
      convert: http://data.fixer.io/api/convert?access_key=%s&from=%s&to=%s&amount=%s
      all-exchange: http://data.fixer.io/api/latest?access_key=%s
server:
  port: 8090

auth:
  audience: currency-service
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-p8m-k2lu.us.auth0.com/
