stock:
    token: XY0nvUJeuBid38SGajAiwYalBsGtdvonlvnrLGUq
    url:
      actual:  https://api.stockdata.org/v1/data/quote?symbols=%s&api_token=%s
      historical-quote: https://api.stockdata.org/v1/data/eod/multiple?symbols=%s&api_token=%s
server:
  port: 8070
